### ISSUE TITLE
If existing project has dash in name while importing timesheet new project is created

### ISSUE THREAD

**Issue by codiflow** [kevinpapst/ImportBundle#11]
### Describe the issue

This is just a small bug which I tested with a recent installation of Kimai Docker, with the newest Importer plugin version and with the CSV import. Don't know if the JSON import is affected too.

If the **project name** contains a **dash** (e.g. like in the German word `IT-Dienstleistungen`) the Importer plugin **always** creates a new project for all timesheet entries with this name on each import.

What I did:
I **precreated** a project named `IT-Dienstleistungen` in Kimai and specified the same project name in my CSV file. But the Importer always creates a **new** project named `IT-Dienstleistungen` which is linked to the specific customer for every import (not every record).

As soon as I **remove the dash** from the precreated project name and adjust the CSV file accordingly it behaves correctly and appends the records to the already existing project in Kimai.

### Kimai version

2.9.0

### How do you run Kimai?

Docker

**Comment by kevinpapst** [comment]
Tested with this file:
[timesheet (1).csv](https://github.com/kevinpapst/ImportBundle/files/13929275/timesheet.1.csv)

First import created 2 projects (as expected).
Next import created 0 projects.

You could debug this place, maybe something is odd with the customer name?
https://github.com/kevinpapst/ImportBundle/blob/424279914bef11c5b10fe6a6e462383a7fb1b502/Importer/AbstractTimesheetImporter.php#L413-L421

**Comment by codiflow** [comment]
That's right and that never was an issue. 😉

But as soon as those projects were already existing in Kimai (having created them **manually AND beforehand** and not by an import) the bug appears 😎

**Comment by codiflow** [comment]
I really don't get it. I did some more tests on this issue as the dash does **not** seem to be the cause. But as soon as the project is named `IT-Dienstleistungen` the issue appears. Also with a completely new created customer.

In my installation there are multiple projects named `IT-Dienstleistungen` but they are all assigned to another customer and during my tests I could confirm that two projects with the same name on different customers are not triggering this.

**Comment by kevinpapst** [comment]
Just tested, only 4 rows are imported if I create the projects manually before.
Add a working test-case CSV please, otherwise I am not putting more of lifetime into this.

**Comment by codiflow** [comment]
I'm working on it – just a few minutes :-)

**Comment by kevinpapst** [comment]
Posting at the same time usually is weird. Take your time, it is Saturday evening anyway...

**Comment by codiflow** [comment]
This is my project list with a test customer `Testkunde` and one letter stripped from the end of `IT-Dienstleistungen` so it is only `IT-Dienstleistunge`:

![image](https://github.com/kevinpapst/ImportBundle/assets/43847817/761242f5-0ad7-41f1-9b67-f836b7fcbc41)

This is the CSV file where the import works:
```csv
Date,From,To,Duration,Rate,User,Customer,Project,Activity,Description,Exported,Tags,HourlyRate,FixedRate,InternalRate
2024-01-05,15:15:00,15:30:00,900,,user@domain.de,Testkunde,IT-Dienstleistunge,Arbeitszeit,Some work description,0,,,,
2024-01-05,16:15:00,16:30:00,900,,user@domain.de,Testkunde,IT-Dienstleistunge,Arbeitszeit,Some work description,0,,,,
```

Result – all fine:
![image](https://github.com/kevinpapst/ImportBundle/assets/43847817/0a1c8af4-baa2-43f2-b16f-b850db6b5fe8)

---

Changing the name to `IT-Dienstleistungen` in Kimai now (I also noticed that they all get the **same color** – don't know if thats a hint helping to track this down) and copying it to the clipboard:

![image](https://github.com/kevinpapst/ImportBundle/assets/43847817/323d5997-65c2-455f-93b9-bf46bd44847a)

Pasting it to the CSV file and checking twice that there are no spaces before/after the string.

This is the CSV file where the import **is creating a new project**:
```csv
Date,From,To,Duration,Rate,User,Customer,Project,Activity,Description,Exported,Tags,HourlyRate,FixedRate,InternalRate
2024-01-05,15:15:00,15:30:00,900,,user@domain.de,Testkunde,IT-Dienstleistungen,Arbeitszeit,Some work description,0,,,,
2024-01-05,16:15:00,16:30:00,900,,user@domain.de,Testkunde,IT-Dienstleistungen,Arbeitszeit,Some work description,0,,,,
```

Result - project is being created although it already exists:

![image](https://github.com/kevinpapst/ImportBundle/assets/43847817/8c33d244-bc29-4ff9-af65-a18ac8d21582)

**Comment by kevinpapst** [comment]
Alright, with that test case, I could reproduce. 
Already have an idea, not sure if it is 100% fixable.
I hope in the real world, there are no two customer with the same name...

**Comment by codiflow** [comment]
Great to hear that and glad that I could be of some help here 😎

I fixed it by just renaming the project temporarily for the import and renaming it back afterwards. As I've just a few customers to import the additional efford is acceptable.

By the way: **THANKS** for this great piece of software. It's a pleasure to use it 🥰

**Comment by kevinpapst** [comment]
https://github.com/kevinpapst/ImportBundle/releases/tag/2.9.0
