### ISSUE TITLE
[Improvement] CSV attribute documentation for Importer

### ISSUE THREAD

**Issue by codiflow** [kevinpapst/ImportBundle#12]
I found a lot of "TODOs" in the importer documentation at https://www.kimai.org/documentation/plugin-import.html#timesheets and as I couldn't find a documentation repository where a pull request could have been made I contribute as follows:

| Attribute | Supported field names |
| --- | --- |
| Duration | Timesheet duration in seconds |
| Tags | Comma separated list of tag-names |
| Exported | Whether the timesheet should be marked as exported or not (1 or 0) |
| Rate | The rate as an integer |
| HourlyRate | The hourly rate as an integer |
| InternalRate | The internal rate as an integer |
| FixedRate | The fixed rate as an integer |
| Billable | Whether the entry should be marked as billable or not (1 or 0) |
| Description | Description of the entry as string |
| Project | Name of the project as string |
| Customer | Name of the customer as string |
| Activity | Name of the activity as string |
| Begin | Start time in the following format: `HH:MM:SS` |
| End | End time in the following format: `HH:MM:SS` |
| Date | Date in the following format: `YYYY-MM-DD` |
| From | TODO … |
| To | TODO … |
| User | Username |
| Email | User email (required when creating users) |

Also for copy & paste:

```
| Attribute | Supported field names |
| --- | --- |
| Duration | Timesheet duration in seconds |
| Tags | Comma separated list of tag-names |
| Exported | Whether the timesheet should be marked as exported or not (1 or 0) |
| Rate | The rate as an integer |
| HourlyRate | The hourly rate as an integer |
| InternalRate | The internal rate as an integer |
| FixedRate | The fixed rate as an integer |
| Billable | Whether the entry should be marked as billable or not (1 or 0) |
| Description | Description of the entry as string |
| Project | Name of the project as string |
| Customer | Name of the customer as string |
| Activity | Name of the activity as string |
| Begin | Start time in the following format: `HH:MM:SS` |
| End | End time in the following format: `HH:MM:SS` |
| Date | Date in the following format: `YYYY-MM-DD` |
| From | TODO … |
| To | TODO … |
| User | Username |
| Email | User email (required when creating users) |
```

Unfortunately I don't know hat the To and From fields are for so I couldn't explain them. Also the `Tags` field was mentioned twice in the documentation – I removed one of them.

**Comment by kevinpapst** [comment]
Source of origin would be here: 
https://github.com/kimai/www.kimai.org/blob/main/_documentation/plugin-import.md

But I can copy & paste and add the missing fields. Thank you!

When documentation is not written immediately, it will be forgotten (at least from by the developer) 😈

**Comment by codiflow** [comment]
Ah thanks, I did not look into that specific repository as it's just called "Website for the Kimai time-tracker" 😅

> When documentation is not written immediately, it will be forgotten (at least from by the developer) 😈

I totally know what you mean 🤪

**Comment by kevinpapst** [comment]
Added in https://github.com/kimai/www.kimai.org/commit/c083429828a4d6a80010215192f84d07e0fcaac2
