### ISSUE TITLE
Importing fails if two or more Customer use the same Project Name

### ISSUE THREAD

**Issue by techsupportkoeln** [kevinpapst/ImportBundle#14]
I have some different Customers and they have the same Project Name, e.g.

Customer | Project | Activities
Customer1 | Service | Remote Support
Customer2 | Service | Remote Support
Customer3 | Service | Remote Support

As i understand, i can set the Activities as Global. But the Projects are always Customer related, but I can use the same name multiple times. The Project ID is different from each one.

Unfortunately, this circumstance causes an error during import.
The importer cannot assign the Project and then wants to create a new Project for this Customer. Also with the same name as the existing Project.

I also tried to import the CSV file with the Project ID shown in the URL, but the importer doesn't seem to recognize the Project ID.

In my case the importer cannot be used because I have to use the same Project names for multiple Customers.

Maybee it's possible to import in the future via Project ID and not only with the Project Name.

**Comment by techsupportkoeln** [comment]
sorry, i have read to late that it is fixed in the last version.

**Comment by techsupportkoeln** [comment]
It's not fixed with the actual Version. In addition, there are problems with customers who have an ä, ö or ü in their names. The Importer likes to create a new Customer in this Case.

Kimai 2.9.0
Importer 2.8.0

![kimai](https://github.com/kevinpapst/ImportBundle/assets/78727046/21fd5b40-f487-49f9-9ea1-6186634c51cc)

**Comment by kevinpapst** [comment]
Original issue is fixed, closing again.

The broken character looks like a "windows does not know how to encode files in UTF-8 properly" issue.
This name is likely not the name of the customer in your system.

After fixing the encoding, be free to create a new issue for a new problem.

But be warned: the importer preview counter is not working correctly for new projects of new customers. Every not found project looks like a new one to the importer.
