### ISSUE TITLE
Importing project creates duplicates customers?

### ISSUE THREAD

**Issue by niels-przybilla** [kevinpapst/ImportBundle#15]
Hello,

I want to import a list of projects with customers.
Importer shows to create 254 projects but also the same amount of customers. 
But some customers have multiple projects. Will the customers really be imported multiple times?

THX and best wishes

Niels

![Monosnap Kimai – Zeiterfassung 2024-04-16 08-10-52](https://github.com/kevinpapst/ImportBundle/assets/99684821/e60a4a53-6d2f-4906-8cb1-6e103dc6820c)

**Comment by kevinpapst** [comment]
The dry-run cannot take all circumstances into account => not persisting objects during this test run can lead to invliad results.

You should always have a backup, best is to test large imports in an isolated environment first.

**Comment by kevinpapst** [comment]
No feedback, closing
