### ISSUE TITLE
Duplicate Activities created when migrating from v1.3.1.1394 to v2.15

### ISSUE THREAD

**Issue by jimlucas** [kevinpapst/ImportBundle#16]
I have an existing installation of Kimai running on CentOS 6.7 with PHP 7.1 and MySQL 5.1.73.

I recently installed Kimai 2.15 on Debian 12 with PHP 8.2.18 and MariaDB 10.11.6.

Using the instructions found here: https://www.kimai.org/documentation/installation.html I installed kimai using the SSH method.

I then used the instructions found here: https://www.kimai.org/documentation/migration-v1.html  to migrate the data over.

Took a couple tries, but I finally got the data migrated.  With each attempt I did drop and re-install the Kimai DB schema.

After the data migrated without any errors, I found that two, sometimes three, Activities were created for each activity that existed on the old system.  It would appear that all related Timesheet entries are associated to only one instance of the duplicated Activities and the duplicate entries appear to have zero time being tracked.

Any suggestions on where to look start looking in the ImportBundle code base to fix this would be greatly appreciated?

**Comment by kevinpapst** [comment]
You can import the activities either global or project specific. 
Default is project specific, so each activity will be created under each project it was used with.

You want to append `--global`, see
https://github.com/kevinpapst/ImportBundle/blob/main/Command/KimaiImporterCommand.php#L158

**Comment by jimlucas** [comment]
Adding `--global` was the key.

Thank you for your help.
