### ISSUE TITLE
Missing class "Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface"

### ISSUE THREAD

**Issue by Breathewave** [kevinpapst/ImportBundle#3]
Full error message shown while reloading Kimai :

[ERROR] Cannot autowire service "KimaiPlugin\ImportBundle\Command\KimaiImporterCommand": argument "$passwordHasher" of method "__construct()" has type "Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface" but this  class was not found.

**Comment by kevinpapst** [comment]
Works if you install the correct version.

**Comment by Breathewave** [comment]
> Works if you install the correct version.

Thanks Kevin, I accidentally picked the wrong file.

**Comment by kevinpapst** [comment]
Will be easier, once 2.0 is released. In the meantime, this mix-up will happen 😁 sorry for the version chaos.
