### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by macbef** [kevinpapst/ImportBundle#4]
Hello, thanks for the great work on kimai!

I have a problem installing ImportBundle (using git).
After cloning the repo and running

  /opt/RZphp81/bin/php-cli bin/console cache:clear --env=prod

I get this error:

 Cannot autowire service "KimaiPlugin\ImportBundle\Command\KimaiImporterCommand": argument "$passwordHasher" of method "__construct()" has type "Symfony\Co
  mponent\PasswordHasher\Hasher\UserPasswordHasherInterface" but this class was not found.

I'm using a Strato webspace

**Comment by kevinpapst** [comment]
See #3

**Comment by macbef** [comment]
Sorry, Kevin... I should have checked the closed issues.

Switching to 1.x helped :)

```
cd var/plugins/ImportBundle
git checkout 1.x
```
