### ISSUE TITLE
Getting different errors when using Importer v1.22

### ISSUE THREAD

**Issue by agichim** [kevinpapst/ImportBundle#5]
Hi Kevin,

I've tried too many times to import a .csv and .json file with Timesheet data and I can't make it work. 

Kimai version: 1.30.0 stable
Plugin version: 1.22 (I understand this is the correct version with my Kimai version).

I get three errors consistently.

1. "The header record contains duplicate column names." - I get this one when uploading the file without "Date, User..." headers. I thought it might be becasue many columns are empty, so I made sure that the first row with data had all cells filled in. Although the first row with data shouldn't act as a header, except if it contains the header titles (Date, User, etc.). 
2. "Something is wrong
A critical error occurred, please try again. You may have found a software problem, please contact your administrator if the problem persists." This happens on different ocassions, I lost count of the circumstances of each edit I made to the data.
3. "Could not find matching importer". This I can only imagine it's because it can't find any actual headers (Data, User, etc.). Which wouldn't make sense, because it throws this error having the header row in the file. 

I have also download the sample file Kimai offers and it upload fine as a preview, than took my data and placed it in the sample file and it throws Error 2.
In the sample file I have written new data from scratch and I get the same Error 2. 
I use LibreOffice, I have also placed the data modified several way in Google Spreadsheets and downloaded the .csv and I get the same error. 

I have stopped many times troubleshooting this whilst I was writing this issue and I'm sorry to say, I had no luck in solving it. 

By the way, in the sample file, the "Tag" data is written over the next two columns so the the info of the "rate columns" are pushed to the right, like so: 
![image](https://user-images.githubusercontent.com/51931067/219184176-10ec5875-d72c-4766-bd7a-0133e1878f61.png)

When this sample file is uploaded with data and column not coinciding it throws no error and I have noticed that it writes the info correctly in the Preview, which shouldn't actually be correct and should throw an error. 
![image](https://user-images.githubusercontent.com/51931067/219188175-7e205e23-db1d-4200-afd0-746ad70ce3b9.png)

The sample file works only if used as is originally, as soon as I save it, even when only duplicated the data contained in the sample file, it throws Error 1. 

I've kept the shift in the columns where the tags were spread over 3 columns and didn't work either. 

I can only think there must be an error in my data, but I'm too tired to look through it now. There are 398 rows with entries. This data I have exported from Kimai 1.11

Thanks for reading.

**Comment by kevinpapst** [comment]
Install this one and retry: https://github.com/kimai/kimai/releases/tag/1.30.6

**Comment by agichim** [comment]
Can I install import via CLI like this `bin/console kimai:import:timesheet`?

**Comment by kevinpapst** [comment]
No feedback, closing

**Comment by agichim** [comment]
Hi, I had actually asked a question last. So I was waiting for your feedback/answer. I do just realise I miswrote a word. 

I meant to say, can I still import via CLI? https://github.com/kevinpapst/ImportBundle/issues/5#issuecomment-1433046998

Thanks
