### ISSUE TITLE
Import of CSV files not working

### ISSUE THREAD

**Issue by SaturnusDJ** [kevinpapst/ImportBundle#6]
Kimai 2.0.0
CSV Importer 2.0.1

Download the CSV example files from the importer page. Try to upload them. It does not work:
`Unsupported file given`

JSON does work.

**Comment by kevinpapst** [comment]
Works for me. Provide more infos

**Comment by SaturnusDJ** [comment]
It did work in MS Edge now. So suspicion goes to Firefox. It did not work on two quite different Windows 10 computers.
Firefox version is 110.1.
Tried in private window: does not work.
Tried without uBlock Origin: does not work.
Tried on Ubuntu: works.

**Comment by SaturnusDJ** [comment]
Not sure if useful but I made this performance dump for you: https://share.firefox.dev/3T38R46
Despite the dump saying Firefox 109, the local browser says 110.0.1. This is back on the initial computer, where I now verified that Google Chrome also works correctly.

This problem with Firefox also occurs on the demo setup at https://demo-empty.kimai.org

**Comment by kevinpapst** [comment]
Maybe you have a over-active security/privacy plugin active? 
Did you try with all deactivated plugins?
<img width="1327" alt="Bildschirm­foto 2023-03-10 um 11 00 37" src="https://user-images.githubusercontent.com/533162/224286449-3333a7ae-19ea-4d15-ac72-d59524cb90aa.png">

**Comment by SaturnusDJ** [comment]
Same in Troubleshoot Mode.
The two setups, both for testing before production, do not have certificates installed and thus do not run via HTTPS. Could that be something?

**Comment by kevinpapst** [comment]
I added some debug logs in the latest version. You could try that and report back.

**Comment by SaturnusDJ** [comment]
After initial setup, we do not use the ImportBundle.

I made a test setup. After installing the plugin, to not get server error 500 I had to `rm -rf /opt/kimai/var/cache/*`

Performed as in topic start. This is the error given: _Unsupported file given, invalid mimetype (text/plain). Try to use another browser._

**Comment by SaturnusDJ** [comment]
This happens in a somewhat restricted work environment and on an unrestricted self-built high-end pc at home. Both use Firefox though. Something is going on with Firefox. I downloaded the example file and immediately uploaded it again.

**Comment by kevinpapst** [comment]
There is something fishy. I cannot explain what.
The code is trying to verify if that is a CSV or JSON file by detecting its mimetype.
I will not open and throw arbitrary files at the import logic, only becuase it is called `.csv`.

I understand it is frustrating, but it is working for everyone else 🤷 
Even here with Firefox (on Mac) and server on multiple Linux and Mac machines.

**Comment by SaturnusDJ** [comment]
Yeah it is strange, but it is okay. After initial setup (months ago now), we do not need Importer. 👌🏼

**Comment by kevinpapst** [comment]
Here is another case: https://github.com/kevinpapst/ImportBundle/issues/6

> Unfortunately, you cannot carry out CSV imports via Firefox. 
> I see the following error on the Kimai Import Page: Unsupported file given, invalid mimetype (text/plain / application/vnd.ms-excel). Try to use another browser.
> With edge it is working.

![kimai_import](https://github.com/kimai/kimai/assets/78727046/2b65ab01-4612-44d8-9679-22e53c3bbe61)

**Comment by kevinpapst** [comment]
It is working in Brave, Chrome, Safari. Edge. It is not working in Firefox. 
Not sure if I want to add a workaround for a broken browser.

**Comment by kevinpapst** [comment]
Haven't heard anything since then, so closing.
