### ISSUE TITLE
Can't install after clean latest Kimai install.. 

### ISSUE THREAD

**Issue by dreamworks** [kevinpapst/ImportBundle#7]
git clone https://github.com/kevinpapst/ImportBundle.git ImportBundle
 bin/console kimai:reload --env=prod

And then I see the following error:

 [ERROR] Cannot autowire service
         "KimaiPlugin\ImportBundle\Command\KimaiImporterCommand": argument
         "$passwordHasher" of method "__construct()" has type
         "Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface"
         but this class was not found.

**Comment by piyushpaliwal** [comment]
same here; were you able to find any solution?

**Comment by kevinpapst** [comment]
I know we are not used to reading anymore...
https://github.com/kevinpapst/ImportBundle/issues?q=is%3Aissue+is%3Aclosed

<img width="472" alt="Bildschirm­foto 2023-04-25 um 08 53 09" src="https://user-images.githubusercontent.com/533162/234197237-74276eb2-3823-4c87-b58f-08e9cfdd7d9f.png">

**Comment by piyushpaliwal** [comment]
yeah, I know the world is moving towards not reading; however, it wasn't the case for me. I did read the docs and threads and thankfully after writing the comment; was able to figure out what was going wrong.
Appreciate the sarcasm 😄
